### ISSUE TITLE
Exported game panics due to missing `ResourceImporterOggVorbis` methods

### ISSUE THREAD

**Issue by dgcole** [godot-rust/gdext#489] opened 2023-11-19 20:27 UTC
I have been encountering the following panic when running exported games using the `custom-godot` feature:
```
ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core\extension\gdextension_interface.cpp:1347)
ERROR: Rust function panicked in file godot-ffi\src\toolbox.rs at line 248. Context: failed to initialize GDExtension level `Scene`
   at: <function unset> (godot-core\src\lib.rs:155)
ERROR: Panic msg:
  Failed to load class method ResourceImporterOggVorbis::load_from_buffer (hash 354904730).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
   at: <function unset> (godot-core\src\lib.rs:101)
```

This same issue seems to happen when using the `custom-godot` feature with the example extension. Here are the steps that I have verified to reproduce the issue (I have only checked on Windows, I can check on Linux too if that would be helpful):

1. Build `editor` and `template_debug` targets for custom godot version (I am using ad72de508 , corresponding to 4.2 rc1).
2. Point `GODOT4_BIN` environment variable at the custom editor build
3. Enable the `custom-godot` feature in `examples/dodge-the-creeps/rust/Cargo.toml` and run `cargo build`.
4. In the editor, use the custom `template_debug` to export a Windows Desktop build of the `dodge-the-creeps` example.
5. Run the game, receive the error above.

**Comment by PgBiel** [comment] 2023-11-19 20:37
Which `gdext` version (commit) are you using?

**Comment by dgcole** [comment] 2023-11-19 20:44
> Which `gdext` version (commit) are you using?

The latest, [8ec6a22](https://github.com/godot-rust/gdext/commit/8ec6a229065396b209f14652334455c92063e342).

**Comment by 0awful** [comment] 2023-12-07 07:26
Additionally: There is an issue that that code block calls out given here: https://github.com/godotengine/godot/issues/81386

It references the `dev` release of `4.2` of `godot`.

In the "Steps to reproduce" of the issue it says:
> In the godot-cpp test project, add call to one of the affected methods. For example: add_child(memnew(Node));
> Set a debugger breakpoint inside MethodBind::get_default_argument with a condition of idx < 0.

Upon the issue being opened `@gdextention` was tagged.

A dialogue occurred which is _very_ above my understanding, from what I can tell it was about a hashing function error that prevented access to compatibility methods therefore breaking gdextension's ability to provide an integration point. (double check this though :joy:) At least two fixes were discussed and gdextension held a meeting, picked the solution, and opened this pr.

https://github.com/godotengine/godot/pull/81521

In that pr we find a portion of the broken code block. https://github.com/godotengine/godot/pull/81521/files#diff-d135db0d106bab2898628c4590eeb7b5e4794e1b25a8a8d23abd47759bbd7296R893-R899

And with @Bromeon commenting :joy:. I didn't expect to find that when I started following threads. But maybe you know more about this issue. Is the fix broken? Are other gdextention consumers experiencing issues?

**Comment by Bromeon** [comment] 2023-12-07 10:55
@0awful I'm not sure if the issue is related. https://github.com/godotengine/godot/issues/81386 is specifically about default parameters -- but [`ResourceImporterOggVorbis::load_from_buffer()`](https://docs.godotengine.org/en/stable/classes/class_resourceimporteroggvorbis.html) doesn't have any.

---

@Lemiczek Thanks, interesting to see that this happens also without `custom-godot`, that should simplify finding the root cause. Just to confirm, you used Godot 4.2-stable with the default export templates (also 4.2)?

This can probably be reproduced with a Godot release build (i.e. without the editor). I have the suspicion that such builds exclude some symbols? That particular [seems to be registered](https://github.com/godotengine/godot/blob/d5ad37afcd44f4ba953e3473b5ab3afb18068134/modules/vorbis/resource_importer_ogg_vorbis.cpp#L123-L123), so I wonder if it's a weird edge case of conditionally disabled code? Or maybe the function is registered, but under a different hash in release mode? Would need some debugging...

As an anecdote, there were a few [cases of missing methods](https://github.com/godotengine/godot/pull/80852) in GDExtension before. If this is the case, all other bindings (godot-cpp etc) will break as well, but they defer the error to runtime, when calling this method. If so, it should be fixed upstream in Godot and not in godot-rust; see also [my position](https://github.com/godot-rust/gdext/issues/423#issuecomment-1732510274) on this matter.

**Comment by Lemiczek** [comment] 2023-12-07 13:39
> you used Godot 4.2-stable with the default export templates (also 4.2)?

Yes, I've used Godot 4.2-stable and downloaded and used the export template for 4.2.
`/home/lemi/.local/share/godot/export_templates/4.2.stable`
`Godot version: v4.2.stable.nixpkgs [46dc27791]`

I've done a sanity check by providing the debug `.so` library instead of the release one after exporting... without anything substantial, it seems to still happen. 🫤

**Comment by Xylord** [comment] 2023-12-11 05:19
Can confirm I encounter this same error while trying to run an exported project in either Windows or Ubuntu. I am not using the custom-godot feature.

**Comment by PgBiel** [comment] 2023-12-11 05:21
@Xylord and others: Can you try enabling the `lazy-function-tables` feature and trying again? We found a similar problem while debugging WASM and that feature fixed it. Perhaps the problem we found actually affects all export targets, not just WASM?

**Comment by Lemiczek** [comment] 2023-12-11 07:16
I can confirm, compiling with `lazy-function-tables` does work :thinking: 

This is still something we should fix without explicitly calling the feature though, at least we have more of an understanding on what's going on. :+1:

**Comment by Bromeon** [comment] 2023-12-11 07:52
Yeah, while that "fixes" it it just moves errors to runtime. If you happen to use one of the functions that are not available, it will work fine on your development machine, and explode on the player's machine. Not recommended.

**Comment by Xylord** [comment] 2023-12-11 08:26
Are the unavailable functions limited to `ResourceImporterOggVorbis::load_from_buffer`, or might there be others that we don't see because the programs panics before trying to load them?

**Comment by Bromeon** [comment] 2023-12-11 08:28
It's likely that there are many others, yes.

Will need to reproduce this at some point and see if there's a pattern.

**Comment by coder137** [comment] 2023-12-12 02:53
Seems like there is a problem only with `ResourceImporterOggVorbis`

Commented out the panic and on exporting and running the game got the following dump

```
ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
ResourceImporterOggVorbis load_from_buffer with 354904730 is null // my prints
ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
ResourceImporterOggVorbis load_from_file with 797568536 is null // my prints
```

Can replicate the problem with this repository example
- `examples/dodge-the-creeps/rust/Cargo.toml`
  - Change to `godot = { path = "../../../godot" }` (experimental wasm seems to work properly)
- Create a simple export_presets for your platform (tested on Windows)
- Following build commands, make sure the `../build` folder is created
```
# From `examples/dodge-the-creeps/godot` folder
cd ../rust
cargo build
cd ../godot
%GODOT4_BIN% --headless --verbose --export-debug "Windows Desktop" ../build/GodotTest.exe
```

**Comment by Bromeon** [comment] 2023-12-13 22:30
@Xylord 

> Can confirm I encounter this same error while trying to run an exported project in either Windows or Ubuntu. I am not using the custom-godot feature.

I can't reproduce it on Windows 10.

Can you guys try with the dodge-the-creeps example from the repo?
I built it with gdext ef5f388def606ee119849e01ac0fafc1e0ec2c2a, compiled both
```
cargo build -p dodge-the-creeps --release
cargo build -p dodge-the-creeps --release --features godot/custom-godot
```
(with `godot4` pointing to 4.2.0-stable). 

I tried running it both directly with the official 4.2.1 export templates, and exporting it from the official 4.2.1 stable editor. Everything seems to work as expected.

**Comment by coder137** [comment] 2023-12-13 22:54
> Seems like there is a problem only with `ResourceImporterOggVorbis`
> 
> Commented out the panic , on exporting and running the game got the following dump
> 
> ```
> ERROR: Parameter "mb" is null.
>    at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
> ResourceImporterOggVorbis load_from_buffer with 354904730 is null // my prints
> ERROR: Parameter "mb" is null.
>    at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
> ResourceImporterOggVorbis load_from_file with 797568536 is null // my prints
> ```
> 
> Can replicate the problem with this repository example
> - `examples/dodge-the-creeps/rust/Cargo.toml`
>   - Change to `godot = { path = "../../../godot" }` (experimental wasm seems to work properly)
> - Create a simple export_presets for your platform (tested on Windows)
> - Following build commands, make sure the `../build` folder is created
> ```
> # From `examples/dodge-the-creeps/godot` folder
> cd ../rust
> cargo build
> cd ../godot
> %GODOT4_BIN% --headless --verbose --export-debug "Windows Desktop" ../build/GodotTest.exe
> ```
> - Run the game with console output from the build folder

@Bromeon can you try the steps listed above.
Need to update the Cargo.toml file in the Dodge the creeps example

**Comment by suikanon** [comment] 2023-12-14 04:31
> @Xylord

I did as you said. Upon starting the game the output below pops up in the console. I had to modify the dodge the creeps project a bit to get it to run. First, in Cargo.toml, I changed the godot dependency to:
```godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["experimental-wasm"] }```

Second, in the .gdextension file, I moved the .dll files to a bin folder in the godot directory, and pointed the .gdextension path there:
```windows.debug.x86_64 = "res://bin/debug/dodge_the_creeps.dll"```
```windows.release.x86_64 = "res://bin/release/dodge_the_creeps.dll"```

The game seems to work properly in-editor.

```Initialize GDExtension API for Rust: Godot Engine v4.2.stable.official
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org

ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
ERROR: Rust function panicked in file /home/xylord/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-ffi/src/toolbox.rs at line 249. Context: failed to initialize GDExtension level `Scene`
   at: <function unset> (/home/xylord/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-core/src/lib.rs:159)
ERROR: Panic msg:
  Failed to load class method ResourceImporterOggVorbis::load_from_buffer (hash 354904730).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
   at: <function unset> (/home/xylord/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-core/src/lib.rs:105)
ERROR: Cannot get class 'Main'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Main of type Main cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: Cannot get class 'Player'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Player of type Player cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'body_entered' to callable 'Node::on_player_body_entered'.
   at: (core/object/object.cpp:1344)
ERROR: Cannot get class 'Hud'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Hud of type Hud cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'hit' to callable 'Node::game_over'.
   at: (core/object/object.cpp:1344)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'start_game' to callable 'Node::new_game'.
   at: (core/object/object.cpp:1344)

It's probably worth noting that the library was compiled on linux Ubuntu using ```cargo build -p dodge-the-creeps --target=x86_64-pc-windows-gnu --release```

**Comment by Xylord** [comment] 2023-12-14 04:32
> @Xylord

I did as you said. Upon starting the game the output below pops up in the console. I had to modify the dodge the creeps project a bit to get it to run. First, in Cargo.toml, I changed the godot dependency to:
```godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["experimental-wasm"] }```

Second, in the .gdextension file, I moved the .dll files to a bin folder in the godot directory, and pointed the .gdextension path there:
```windows.debug.x86_64 = "res://bin/debug/dodge_the_creeps.dll"```
```windows.release.x86_64 = "res://bin/release/dodge_the_creeps.dll"```

The game seems to work properly in-editor.

```Initialize GDExtension API for Rust: Godot Engine v4.2.stable.official
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org

ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
ERROR: Rust function panicked in file /home/xylord/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-ffi/src/toolbox.rs at line 249. Context: failed to initialize GDExtension level `Scene`
   at: <function unset> (/home/xylord/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-core/src/lib.rs:159)
ERROR: Panic msg:
  Failed to load class method ResourceImporterOggVorbis::load_from_buffer (hash 354904730).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
   at: <function unset> (/home/xylord/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-core/src/lib.rs:105)
ERROR: Cannot get class 'Main'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Main of type Main cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: Cannot get class 'Player'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Player of type Player cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'body_entered' to callable 'Node::on_player_body_entered'.
   at: (core/object/object.cpp:1344)
ERROR: Cannot get class 'Hud'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Hud of type Hud cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'hit' to callable 'Node::game_over'.
   at: (core/object/object.cpp:1344)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'start_game' to callable 'Node::new_game'.
   at: (core/object/object.cpp:1344)

It's probably worth noting that the library was compiled on linux Ubuntu using ```cargo build -p dodge-the-creeps --target=x86_64-pc-windows-gnu --release```

**Comment by Bromeon** [comment] 2023-12-14 07:59
Thanks @coder137 and @Xylord, I overlooked that the default dependencies of `dodge-the-creeps` only have a minimal set of classes.

Changed its `Cargo.toml` to:
```toml
[dependencies]
godot = { path = "../../../godot" }
rand = "0.8"
```
And built with:
```
cargo build -p dodge-the-creeps --release
```

Then indeed, I can reproduce it! 👍 
```rs
ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1347)
ERROR: Rust function panicked in file godot-ffi\src\toolbox.rs at line 249. Context: failed to initialize GDExtension level `Scene`
   at: <function unset> (godot-core\src\lib.rs:159)
ERROR: Panic msg:
  Failed to load class method ResourceImporterOggVorbis::load_from_buffer (hash 354904730).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
   at: <function unset> (godot-core\src\lib.rs:105)
ERROR: Cannot get class 'Main'.
   at: (core/object/class_db.cpp:358)
WARNING: Node Main of type Main cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:254)
ERROR: Cannot get class 'Player'.
...
```

So that's a start 🙂

**Comment by Bromeon** [comment] 2023-12-15 17:41
Confirmed with Godot developers and tracked as https://github.com/godotengine/godot/issues/86206.

I will implement a workaround in gdext, until there is an official way to know about methods that are unavailable in Release mode.

**Comment by LinuxUserGD** [comment] 2023-12-17 03:06
Enabling the  `lazy-function-tables` feature fixes the errors when loading `dodge-the-creeps` on Gentoo Linux [godot-4.2.1](https://data.gpo.zugaina.org/gentoo/dev-games/godot/godot-4.2.1.ebuild), likely because compiling from source with different scons build options results in a different `extension_api.json`.

```bash
diff --git a/examples/dodge-the-creeps/rust/Cargo.toml b/examples/dodge-the-creeps/rust/Cargo.toml
index c45f9d4..e709ba0 100644
--- a/examples/dodge-the-creeps/rust/Cargo.toml
+++ b/examples/dodge-the-creeps/rust/Cargo.toml
@@ -9,5 +9,5 @@ publish = false
 crate-type = ["cdylib"]
 
 [dependencies]
-godot = { path = "../../../godot", default-features = false, features = ["experimental-wasm"] }
+godot = { path = "../../../godot", default-features = false, features = ["lazy-function-tables"] }
 rand = "0.8"
```

<details>

```bash
E 0:00:00:0392   gdextension_classdb_get_method_bind: Parameter "mb" is null.
  <C++ Source>   core/extension/gdextension_interface.cpp:1347 @ gdextension_classdb_get_method_bind()
E 0:00:00:0392   <function unset>: Rust function panicked in file godot-ffi/src/toolbox.rs at line 249. Context: failed to initialize GDExtension level `Scene`
  <C++ Source>   godot-core/src/lib.rs:159 @ <function unset>()
E 0:00:00:0392   <function unset>: Panic msg:
  Failed to load class method AnimationPlayer::set_process_callback (hash 1663839457).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
  <C++ Source>   godot-core/src/lib.rs:105 @ <function unset>()
E 0:00:00:0434   instantiate: Cannot get class 'Main'.
  <C++ Error>    Parameter "ti" is null.
  <C++ Source>   core/object/class_db.cpp:358 @ instantiate()
E 0:00:00:0434   instantiate: Cannot get class 'Player'.
  <C++ Error>    Parameter "ti" is null.
  <C++ Source>   core/object/class_db.cpp:358 @ instantiate()
E 0:00:00:0434   connect: In Object of type 'Node': Attempt to connect nonexistent signal 'body_entered' to callable 'Node::on_player_body_entered'.
  <C++ Error>    Condition "!signal_is_valid" is true. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   core/object/object.cpp:1344 @ connect()
E 0:00:00:0434   instantiate: Cannot get class 'Hud'.
  <C++ Error>    Parameter "ti" is null.
  <C++ Source>   core/object/class_db.cpp:358 @ instantiate()
  ```
  
  </details>

**Closed** 2023-12-17 15:38 UTC
Labels: bug, status: upstream, c: engine
