### ISSUE TITLE
when using CanvasItem as the base class, the class does not appear in Godot editor picker

### ISSUE THREAD

**Issue by AlexOkafor** [godot-rust/gdext#429] opened 2023-09-27 00:38 UTC
Hello,

I ran across this when trying to move a base class of Node to  something more specific (`CanvasItem`). My current workaround has been to use `Control` instead. 
```rust
#[derive(GodotClass)]
#[class(base=CanvasItem)]
pub struct TestItem {
    #[base]
    base: Base<CanvasItem>,
}

#[godot_api]
impl CanvasItemVirtual for TestItem {
    fn init(base: Base<CanvasItem>) -> Self {
        Self { base }
    }
}

#[godot_api]
impl TestItem {}
```
When using the above snippet, the class doesn't appear in the godot editor. Also if I refactor a class to use CanvasItem as a base class the editor will show errors like so:
```bash
ERROR: Class 'TestItem' or its base class cannot be instantiated.
   at: (core/object/class_db.cpp:341)
```
I did see that CanvasItem is an abstract base class so I wasn't sure if that's related, a technical limitation of the GDext bindings, or this is working as designed w.r.t. GD extensions.

**Comment by Bromeon** [comment] 2023-09-27 06:34
Thanks for reporting! 

I wonder if we need to do something specific for abstract base classes 🤔 this should be possible.

**Comment by PgBiel** [comment] 2023-09-29 18:03
This seems to be on the Godot side: https://github.com/godotengine/godot/pull/67510 and https://github.com/godotengine/godot/pull/67512

**Comment by aaronfranke** [comment] 2024-02-25 00:49
This is working as intended, the intention is that you are not allowed to extend abstract types. So you are not allowed to make your own CanvasItem-derived type. See the reasoning here: https://github.com/godotengine/godot/pull/67510#issuecomment-1959194590

**Comment by Bromeon** [comment] 2024-02-25 13:40
Thanks a lot @aaronfranke for clarifying!
Since this is an upstream design decision, I'll close this.

**Closed by Bromeon** 2024-02-25 13:40 UTC
Labels: bug, status: upstream, c: engine
