### ISSUE TITLE
get() function of Array Panics when Element is empty

### ISSUE THREAD

**Issue by Masupell** [godot-rust/gdext#955] opened 2024-11-29 17:17 UTC
When trying to get an item from an Array which got its size manually added in the godot editor and therefore contains no actual items, but only <empty> fields, it panics when trying to get it, with no way of preventing it

**Comment by Bromeon** [comment] 2024-11-30 08:26
Oh, interesting case, thanks for reporting!

Can you also reproduce this in GDScript, when calling [`Array.resize()`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-resize)?

**Comment by Bromeon** [comment] 2024-11-30 08:35
There's a general issue that array representations in Rust are a bit more strict than in Godot:
- `Array[Class]` can store nulls, but `Array<Gd<Class>>` cannot. Would need `Array<Option<Gd<Class>>>`.
- `Array[int]` may be represented as `Array[u8]` on Rust side 
    - See #853.

In this case, there's the problem that Godot expects arrays to be default-constructible, but godot-rust allows them to have arbitrary constructors (and not necessarily a default one). So there's a good chance this issue would be a `wontfix` due to this discrepancy; requiring default construction just for this use case would be too limiting.

But maybe there are ways we can improve the user experience, e.g. panic message -- how does it look now?

**Comment by Bromeon** [comment] 2024-12-07 15:50
So, as mentioned above, I don't think we can fix this -- at least not without crippling `Array` and only allowing "godot-safe" types. This would mean everyone had to use `Option<Gd<T>>` for objects inside arrays, no `i16` and no `DynGd`.

I'm not sure this is worth it. Some users only use Godot APIs from Rust and aren't affected by the limitation, but can definitely benefit from better Rust-side type safety.

I documented this behavior in `Array` [under section _Element type safety_](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Array.html#element-type-safety). As such I'll close this as wontfix. If you have more ideas how we could handle such cases, let me know!

**Closed by Bromeon** 2024-12-07 15:50 UTC
Labels: bug, c: core
