### ISSUE TITLE
godot_api attribute proc macro hits new rust-analyzer orphan trait implementation checks

### ISSUE THREAD

**Issue by DamnWidget** [godot-rust/gdext#490] opened 2023-11-20 18:09 UTC
# Abstract

The `rust-analyzer` LSP made a new release recently introducing a new feature for diagnose orphan trait implementation cases https://github.com/rust-lang/rust-analyzer/pull/15895

Godot crate hits this new check wherever `#[godot_api]` attribute proc macro is being used

![image](https://github.com/godot-rust/gdext/assets/329766/3ab46d7b-bf90-4b69-90a9-ceccb62d9d05)

## Workaround

I did not found a setting in `rust-analyzer` to disable the check so the only workaround for now is to downgrade your `rust-analyzer` version to a lower one. 

P.S: if there is a setting to disable this check, please, let me know

**Comment by PgBiel** [comment] 2023-11-20 18:50
Is it not this check? https://github.com/rust-lang/rust-analyzer/pull/15895

Also, are you using the latest `rust-analyzer`? Have you tried using the latest nightly/preview version of it as well?

**Comment by DamnWidget** [comment] 2023-11-20 19:11
> Is it not this check? [rust-lang/rust-analyzer#15895](https://github.com/rust-lang/rust-analyzer/pull/15895)

I was browsing their issues tracker and looks like I messed up the copy and paste, it was exactly that pull request the one that I wanted to refer to, fixed my original post. Thanks for pointing out.
 
> Also, are you using the latest `rust-analyzer`? Have you tried using the latest nightly/preview version of it as well?

I am using the latest released version https://github.com/rust-lang/rust-analyzer/releases/tag/2023-11-20 , I just tried their nightly version and hit the same check

**Comment by lilizoey** [comment] 2023-11-20 19:51
oh is that what the issue is. it's a pretty simple fix at least. just gotta change this
https://github.com/godot-rust/gdext/blob/8ec6a229065396b209f14652334455c92063e342/godot-macros/src/class/godot_api.rs#L225
to
```rs
impl ::godot::private::Cannot_export_without_godot_api_impl for #class_name {
  const EXISTS: () = ();
}
```
but it also seems like RA is fixing it here https://github.com/rust-lang/rust-analyzer/pull/15911

**Comment by PgBiel** [comment] 2023-11-20 20:58
I think we can just consider it an upstream problem then, since that would probably cause tons of warnings in several other codebases (and the fix will probably be in the next rust-analyzer release)...

Let's wait for the next rust-analyzer release to confirm.

**Comment by Young-Flash** [comment] 2023-11-21 01:39
Hi, rust-analyzer PR https://github.com/rust-lang/rust-analyzer/pull/15911 got merged, which fix the problem. The next nightly release will be avaliable in a few days (actually there just make a release yesterday but we miss the patched PR to merge)

**Closed** 2023-11-27 16:11 UTC
Labels: quality-of-life, status: upstream, c: bind
