### ISSUE TITLE
Hot reloading Panics in Godot

### ISSUE THREAD

**Issue by jgunzelman88** [godot-rust/gdext#922] opened 2024-10-18 17:34 UTC
Every time I compile I get the following error requiring me to restart godot.

`
  /Users/<>/.cargo/git/checkouts/gdext-76630c89719e160c/8ad9cb0/godot-core/src/private.rs:393 - Rust function panicked at /Users/<>/.cargo/git/checkouts/gdext-76630c89719e160c/8ad9cb0/godot-core/src/meta/class_name.rs:216.
    Context: failed to initialize GDExtension level `Scene`
  /Users/jgunzelman/.cargo/git/checkouts/gdext-76630c89719e160c/8ad9cb0/godot-core/src/private.rs:407 - [panic]  index out of bounds: the len is 0 but the index is 1
  /Users/<>/.cargo/git/checkouts/gdext-76630c89719e160c/8ad9cb0/godot-core/src/private.rs:393 - Rust function panicked at /Users/<>/.cargo/git/checkouts/gdext-76630c89719e160c/8ad9cb0/godot-core/src/registry/class.rs:219.
    Context: failed to initialize GDExtension level `Editor`
  /Users/<>/.cargo/git/checkouts/gdext-76630c89719e160c/8ad9cb0/godot-core/src/private.rs:407 - [panic]  global lock for loaded classes poisoned; class registration or deregistration may have panicked

`

**Comment by Bromeon** [comment] 2024-10-18 18:19
Duplicate of #871?

Is your dynamic library not properly unloaded?

**Comment by jgunzelman88** [comment] 2024-10-18 19:55
I is a duplicate of 871 sorry I am reading it now.  So do I have to remove it from the project folder for hot reloading to work?  I was working before in 4.2 ever since I switched to 4.3 it hasn't worked.

**Comment by jgunzelman88** [comment] 2024-10-18 20:01
So I just tested on my windows machine.  And I don't see this issue ..... So it might be a MacOS issue.

**Closed** 2024-10-18 21:07 UTC
