### ISSUE TITLE
process method ran even in editor

### ISSUE THREAD

**Issue by manglemix** [godot-rust/gdext#357] opened 2023-07-23 15:47 UTC
I'm writing a simple binding to an `axum` http service, but I notice, among a few issues, that the node I've created immediately starts running `process` as soon as it is added to the scene tree in the *editor*

Rust project: [rustext.zip](https://github.com/godot-rust/gdext/files/12139058/rustext.zip)
Simply add the `HTTPServer` node to a scene and run the scene. You will see a printline indicating that the `process` method is being called

**Comment by B4rc1** [comment] 2023-07-23 16:09
This is the intended behavior, see https://github.com/godot-rust/gdext/issues/70.

You can check if you are running in editor via:
```rust
Engine::singleton().is_editor_hint()
```

**Comment by lilizoey** [comment] 2023-07-23 16:51
> This is the intended behavior, see #70.
> 
> You can check if you are running in editor via:
> 
> ```rust
> Engine::singleton().is_editor_hint()
> ```

it's not intended behavior, it's just the default behavior of gdextension. it'll probably be changed eventually.

**Comment by lilizoey** [comment] 2023-07-23 16:55
Oh I've never tried this before, but

Duplicate of #70

**Closed** 2023-07-23 18:32 UTC
Labels: status: duplicate
