### ISSUE TITLE
Wrong signature in methods like PhysicsServer3D::body_test_motion where there are default null parameters

### ISSUE THREAD

**Issue by kulkalkul** [godot-rust/gdext#294] opened 2023-06-02 10:40 UTC
Comparing the two, Rust counterpart should be Option\<Gd\<PhysicsTestMotionResult3D\>\>:

<https://docs.godotengine.org/en/stable/classes/class_physicsserver3d.html#class-physicsserver3d-method-body-test-motion>
<https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.PhysicsServer3D.html#method.body_test_motion>

**Comment by Bromeon** [comment] 2023-06-02 10:49
Thanks for reporting! This looks like a duplicate of #156, as such I'm closing it.

**Closed by Bromeon** 2023-06-02 10:49 UTC
