### ISSUE TITLE
Hot reloading issues

### ISSUE THREAD

**Issue by Jacob-Steentoft** [godot-rust/gdext#608] opened 2024-02-13 20:51 UTC
Hi,

I stumbled over #434 and tried to replicate the steps from the original post to get hot reloading working. But when compiling changes while the game is running, I'm just getting an error `Access is denied. (os error 5)` since the dll file cannot be removed.

Am I misunderstanding the hot reloading capabilities, or is something not working as intended? I'm unable to find any documentation for gdext on the hot reloading on either Godot's docs or the Godot rust book.

**Comment by Bromeon** [comment] 2024-02-13 22:30
Hello 🙂 

Hot reloading is managed by the Godot engine for the most part -- we hook up some callbacks and tell Godot where the `.dll` file is, but the actual reloading is triggered by Godot.

Do you use a recent engine version (at least 4.2)? You also need to set your extension as `reloadable` in the `.gdextension` file.

If the problem persists, I'd recommend opening an issue in Godot's own tracker (or asking on their forum/contributors chat).

**Comment by scripturial** [comment] 2024-02-18 08:30
@Jacob-Steentoft  Hot reloading doesn't work at all on Mac as far as I can tell, even when the reloadable flag is set with the latest version of Godot and rust gdext.  When I rebuild (app running or not), I can't see any changes until I fully quit and restart Godot. (At which point Godot crashes and I reopen and it works)

**Comment by Bromeon** [comment] 2024-02-18 13:03
There are two open bugs related to hot reloading:
- https://github.com/godot-rust/gdext/issues/543
- https://github.com/godot-rust/gdext/issues/582

Can you check if this issue could be related to one of those?

If not, could you report this upstream in the Godot issue tracker? Hot reloading being completely broken on macOS is definitely not something that should happen.

**Comment by Bromeon** [comment] 2024-03-05 13:27
Closing as I can't reproduce it on Windows and haven't gotten more info. Godot implemented [a dedicated mechanism](https://github.com/godotengine/godot/pull/80188) to move DLLs before hot reloading, and from what I can tell, it works.

Regarding the macOS issues, we don't do anything different for that platform. If it still doesn't work, I'd recommend opening an issue on the Godot repo.

**Closed by Bromeon** 2024-03-05 13:27 UTC

**Comment by scripturial** [comment] 2024-03-15 07:18
I haven't tested on 4.3.x yet, but for informational purposes, on macOS, I can confirm the problem is not fixed 4.2.1, I am doing a "quit Godot, build, open Godot" build cycle at the moment.

**Comment by Bromeon** [comment] 2024-03-15 08:38
@scripturial are you sure it is _this_ specific issue with hot reloading though -- with `Access is denied. (os error 5)`?

There are some other hot reloading problems we need to address, but this one is probably something that should be reported to Godot directly, as they're doing the DLL copy logic before reloading.
