### ISSUE TITLE
Faulty InputMap action doesn't exist error message.

### ISSUE THREAD

**Issue by jiaxiongjiao** [godot-rust/gdext#132] opened 2023-02-25 03:09 UTC
When adding 
```rust
// let input = Input::singleton();
// -----
if input.is_action_pressed("my_own_action".into(), false) { 
    // actions
}
// -----
```
to `process` or `physics_process` in `GodotExt` trait. Godot would report this "my_own_action" does not exist. This is not true 
because
1. In Project Settings -> Input Map, "my_own_action" is indeed there.
2. When I run the game, error messages disappear and godot can even perform corresponding action to "my_own_action" when I press the action's key.

This behaviour can be replicated on the example game.
1. add a new action, for example, "print_action" with key "M Physical"
2. In `player.rs` -> `fn process`, add 
```Rust
if input.is_action_pressed("print_action".into(), false) {
    prints("print_action pressed!!!".to_variant(), &[]);
}
```
at the end of action checking
3. Build rust extension
4. Go to Godot and save project
5. The next time you open the project, the output section would keep printing the same red error messages over and over again
saying there is no such action when the game is not even running yet.

**Comment by sayaks** [comment] 2023-02-27 12:47
i believe this is just a consequence of #70 so should be fixed when that is

**Comment by sayaks** [comment] 2023-03-03 20:09
Just to confirm my theory, i made a script
```gdscript
@tool extends Node2D

func _process(delta):
	if Input.is_action_just_pressed("asd"):
		pass
```
and added an action "asd" to the input map. It has the same behavior. So the issue is probably just that the code is running in the editor.

**Comment by atrefonas** [comment] 2023-03-07 22:43
I experienced the issue as well. The code is running in the editor for whatever reason. You can work around it by doing:

let input_map = InputMap::singleton();
if input_map.has_action("print_action".into()) {
  if input.is_action_pressed("print_action".into(), false) {
      prints("print_action pressed!!!".to_variant(), &[]);
  }
}

**Comment by sayaks** [comment] 2023-03-07 22:58
> I experienced the issue as well. The code is running in the editor for whatever reason. You can work around it by doing:
> 
> ```
> let input_map = InputMap::singleton();
> if input_map.has_action("print_action".into()) {
>   if input.is_action_pressed("print_action".into(), false) {
>       prints("print_action pressed!!!".to_variant(), &[]);
>   }
> }
> ```

There's also the usual workaround of doing `Engine::singleton().is_editor_hint()` to check whether the code is running the editor

**Comment by Bromeon** [comment] 2023-03-07 23:20
> The code is running in the editor for whatever reason.

That reason is called GDExtension 😉 
See #70, also linked above.

**Closed** 2023-07-30 13:03 UTC
Labels: bug, c: engine

**Comment by 0x53A** [comment] 2024-11-03 18:56
I hit the same issue and found a solution:

```rust
InputMap.load_from_project_settings()
```

full credit to https://www.reddit.com/r/godot/comments/194l8dc/comment/khgv4hw/
