### ISSUE TITLE
Callable does not support bind calls

### ISSUE THREAD

**Issue by atrefonas** [godot-rust/gdext#169] opened 2023-03-11 14:43 UTC
The Callable struct in gdext does not have bind() or bindv(), which is a useful way to add extra arguments to Godot's built-in signals, for example identifying which button was pressed, or which area was entered, if they are made programmatically.

https://docs.godotengine.org/en/stable/classes/class_callable.html#class-callable-method-bind

I assume this was simply not implemented yet?

**Comment by sayaks** [comment] 2023-03-11 14:50
Yes, as noted in #24, `Callable` is very basic at the moment.

**Comment by atrefonas** [comment] 2023-03-11 14:58
Thanks, I am trying to figure out how to make a good workaround using GDScript for now which doesn't require making a custom class for everything.

**Comment by atrefonas** [comment] 2023-03-12 02:28
Not sure if anyone is too interested but I figured out a decent workaround using GDScript:

```gdscript
func register_signal_with_name(node_path, sig_name, func_call):
	var node = get_node(node_path)
	var callable = Callable(self, func_call).bind(node.name)
	node.connect(sig_name, callable)
```

Example using rust:

```rust
      self.base.call(StringName::from("register_signal_with_name"), &[area_path.to_variant(), 
        "body_entered".to_variant(),
        "on_body_entered".to_variant()]);
```

```rust
    #[func]
    fn on_body_entered(&mut self, name: Variant) {
       godot_print!("on body entered! {:?}", name);
    }

```

**Comment by sayaks** [comment] 2023-03-12 13:44
for that to work, on_body_entered should look like:
```rs
    #[func]
    fn on_body_entered(&mut self, body: Variant, name: Variant) {
       godot_print!("on body entered! {:?}", name);
    }
    ```
    since the `body_entered` signal already passes along an argument.

**Comment by atrefonas** [comment] 2023-03-12 13:47
Yes, actually just figured this out myself 10 minutes ago!

**Comment by sayaks** [comment] 2023-03-16 15:14
this is an upstream issue https://github.com/godotengine/godot-cpp/issues/802

**Comment by Lamby777** [comment] 2023-09-17 13:28
maybe fixed in https://github.com/godotengine/godot-cpp/pull/1091 ...? the original issue was closed 2 weeks ago

**Comment by lilizoey** [comment] 2023-09-17 14:00
oo we should definitely check that out

**Comment by Bromeon** [comment] 2023-09-17 19:53
In that case I'll close it as a duplicate of https://github.com/godot-rust/gdext/issues/382.

**Closed by Bromeon** 2023-09-17 19:53 UTC
Labels: feature, status: upstream, c: core
