### ISSUE TITLE
Implement std::io traits for FileAccess

### ISSUE THREAD

**Issue by fpdotmonkey** [godot-rust/gdext#446] opened 2023-10-08 19:04 UTC
API users interested in File IO in the res:// and user:// file systems need to work with Godot's `FileAccess` API.  gdext should provide a Rusty API for this by implementing some subset of `std::io::{BufRead, IsTerminal, Read, Seek, Write}` for `godot::engine::FileAccess`.

**Comment by Bromeon** [comment] 2023-10-08 21:19
There is a more general question, regarding how far gdext should go and make engine APIs rusty. We would end up with conflicting APIs, e.g.
```rs
fn FileAccess::seek(position: i32);
fn Seek::seek(&mut self, pos: SeekFrom) -> Result<u64>;
```
Even if we can resolve naming conflicts, modifying `godot::engine` classes would be quite unprecedented, so it would be good to have a more general strategy. Maybe it makes sense to define Rusty wrapper types for some example -- similar to how we provide extensions for `load()` and `get_node_as()`?

Can you elaborate what motivated your use case, beyond "it's possible"? 🙂

**Comment by fpdotmonkey** [comment] 2023-10-08 22:44
This came up in a discussion on Discord on getting data for a SQLite table into a relevant library where we found that getting the bytes for a files to require some massaging.  However, I think that case landed on finding a better solution, and I dont personally have an application for it.  So firmly in the realm of its possible and sounds reasonable.

**Comment by PgBiel** [comment] 2023-10-08 23:23
> Maybe it makes sense to define rusty wrapper types -- similar to how we provide extensions for `load()` and `get_node_as()`?

I think that makes more sense, and we could perhaps even decouple the wrappers from the underlying Godot things - have something that just works:tm: by using the underlying Godot APIs for it (and, if you need full flexibility, then just call them manually). In this example, we'd have some Filesystem wrapper or something which uses FileAccess and similar things under the hood.

(Of course, we could be kinda limited in the amount of decoupling possible since e.g. it could be necessary to place a node in the scene tree or something like that. But, in principle, it could be a nice path to follow.)

**Comment by StatisMike** [comment] 2023-11-08 06:42
So I've implemented `Read` and `Write` on a `FileAccess` wrapper struct in my project. The implementation allows serializing and deserializing binary data on the fly, without ever loading whole Vec<u8> in the memory. There are some hacky things there, so it is intended to be a part of exported API of my crate. These hacky things allows to read and write additional data at the beginning of the file, without `seek`ing the positions, just using the built-in functionality of `FileAccess` which moves the cursor automatically after `get_*` and `store_*` calls.

https://github.com/StatisMike/godot_io/blob/3-provide-binary-saving-format/godot_io_defs/src/bin_resource.rs#L13-L111

With some pointers of how this functionality could be done safer, and more useful and how it should be implemented into `gdext` I would happily try to provide a good quality PR.

**Comment by StatisMike** [comment] 2023-11-08 18:59
@Bromeon This is something I came upon after cleaning up the implementation mentioned above. Any pointers, also regarding the style in which it could be implemented in `gdext`?

https://github.com/StatisMike/godot_io/blob/3-provide-binary-saving-format/godot_io_defs/src/file_access.rs

**Comment by Bromeon** [comment] 2023-11-09 12:41
@StatisMike thanks for the initial implementation!

Some feedback: the current implementation is quite a thin and transparent wrapper around `Gd<FileAccess>`. We could maybe provide the most commonly used APIs directly on the wrapper class. Concretely:

- There could be an `open` method just like [`File::open()`](https://doc.rust-lang.org/std/fs/struct.File.html#method.open)
- Some documentation would be nice, notably:
   - That the type is reference-counted.
   - That `Drop` will _not_ close the file, but only when the last reference goes out of scope.
- Name `FaWrapper` is not very descriptive, I would name the struct `GodotFile` or so.
- Instead of the 3 get variants, I would just provide a method `fn to_inner() -> Gd<FileAccess>` which copies the pointer, we can see if more is needed. If the API on the wrapper is rich enough, such cases should be rare.

**Comment by StatisMike** [comment] 2023-11-09 20:36
@Bromeon No worries, I like to Rust and happy to discuss it and happy to provide a good quality code to the community :)

> I wouldn't worry about performance here. We're doing disk access, sometimes even with encryption or compression; a few indirect function calls don't fall into weight. If they do, users are free to always use FileAccess directly. This wrapper is primarily for convenience.

This calms me down a little, wrapper methods will then always check for errors and will actually produce `std::io::Result<T>`. I feel like this is more `rusty` way of doing things than returning `T` and hoping for the best. 

AD the `exposing inner`, I think that wrapping most methods will be actually for the best and will actually make the possibility of needing an `FileAccess` itself perfectly menageable:

```rust
pub struct GFile {
  // The FileAccess is kept as private
  fa: Gd<FileAccess>,
  pos: u64,
  buffer: Vec<u8>,
  buffer_size: usize
}

impl GFile {
 // New GFile is constructed by calling GFile::open_* methods
   pub fn open(path: GodotString, flags: ModeFlags) -> std::io::Result<Self> { ... }
   pub fn open_compressed(path: GodotString, flags: ModeFlags, compression_mode: CompressionMode) -> std::io::Result<Self> { ... }
   pub fn open_encrypted(path: GodotString, flags: ModeFlags, key: PackedByteArray) -> std::io::Result<Self> { ... }
   pub fn open_encrypted_with_pass(path: GodotString, flags: ModeFlags, pass: GodotString) -> std::io::Result<Self> { ... }
 // User can retrieve the `Gd<FileAccess>` from `GFile` by destroying the wrapper
  pub fn into_inner(self) -> Gd<FileAccess> {
    self.fa
  }
  
  // And can also create the `GFile` from the `Gd<FileAccess>` anytime they want:
  impl From<Gd<FileAccess>> for GFile {
  fn from(value: Gd<FileAccess>) -> Self {
    let pos = value.get_position();

    Self {
      fa: value,
      pos,
      buffer: Vec::new(),
      buffer_size: Self::DEFAULT_BUFFER_SIZE
    }
  }
}
```
If you feel that it is a deal-breaker, I will call `get_position()` to get updated position from Godot on every operation and skip relying on it in `GFile` (outside of `Read`, `Write` and `BufRead` trait implementations, which I feel that should be as optimized as they can). Or fall back to your proposition of keeping the internal position as `None`

**Comment by Bromeon** [comment] 2023-11-10 08:59
Yes, definitely skip those methods which are available in `std::io`.

About reading/writing integers of various sizes, should we provide this on the wrapper types? I guess yes?
The problem is that they assume a given endianess, but I guess that's OK if Godot sticks to one.

I would also rename them slightly, starting with `read_` and `write_`.
Example:
```rs
pub fn read_u8(&mut self) -> IoResult<u8> {
    self.read_internal(FileAccess::get_8) // maybe closure needed
}

fn read_internal<T, F>(&mut self, read_fn: F) -> IoResult<T>
where
    F: Fn(&FileAccess) -> T,
{
    let val = read_fn(&*self.inner);
    self.check_error()?;
    self.pos += std::mem::size_of::<T>();
    Ok(val)
}
```
(probably needs some tweaks, but that's the general idea).

Feel free to open a pull request, it's easier to comment on concrete code lines than having a discussion here, and the code being referred to is also not lost over time.

---

One thing that's still a bit problematic: if we allow reference-counting, we can still concurrently modify the file pointer. Not just in threads (this is not thread-safe, which is fine), but basically a `&mut GFile` does not mean I have exclusive access to it. I guess it's OK for a start, but would need to be documented.

An alternative would be to make it more strict, but then we can't allow sharing. So instead of `to_inner()` we would have `into_inner()` that consumes the unique object, so at that point there's no `GFile` anymore. Not sure if that's ergonomic in practice though, so I'd start without it.

**Comment by StatisMike** [comment] 2023-11-10 09:34
I've actually removed the `pos` field completely. My overestimation of its usefulness came from initial focus on traits, namely `Read` would use it extensively to spare calls through `FileAccess::get_position()`. After reviewing it again, I deemed it as overcomplicated, especially if `FileAccess::get_error()` was already called to check for eventual error during operations. `get_position()` is now called at the beginning of every `GFile::read()` operation.  

Another strange thing I've seen is that the `FileAccess::get()` calls are marked as non-mutable, which can be interpreted wrongly - the cursor on the Godot side is moved, even if the file itself isn't changed at all. Additionally, `get_pascal_string()` is the sole `get_*` method that is actually called mutably

**Comment by Bromeon** [comment] 2023-11-10 10:20
> Another strange thing I've seen is that the `FileAccess::get()` calls are marked as non-mutable, which can be interpreted wrongly - the cursor on the Godot side is moved, even if the file itself isn't changed at all.

Yeah, Godot's API is full of wrong const-correctness, unfortunately. Something we can fix in Rust though 🙂 




> After reviewing it again, I deemed it as overcomplicated,

To me it seemed like the `position` would be used as long as we are still in "Rust mode", and it's safe to say that no one else modifies the position of the `FileAccess`, because the latter is locked away. It's fine to always use Godot's position, but this part didn't seem overly complex to me; maybe I'm missing something?

**Comment by StatisMike** [comment] 2023-11-10 10:29
I've opened the WIP PR with current work, most of the documentation is still missing. I also plan to create `itest`s, at least for trait implementations and error handling, which are the sole substantial additions above simle Godot functions redirection.

> I would also rename them slightly, starting with `read_` and `write_`.

Renaming the functions to `read_*` and `write_*` could actually make a clash with some FileAccess methods. Eg. `Read` provides `read_line()` method, which returns `String`, but there is `get_line()` method on FileAccess that returns `GodotString` - unless we want to  ditch the `GodotString` returning method for `String` returning one.

`position` is possibly needed only in `read()` method (where it potentially could get expensive for repeated calls) and in `Seek` trait implementation, and only when moving cursor while basing on `SeekFrom::Current()` (which I don't think will be used as much, actually). The problem steems from implementing `From<Gd<FileAccess>>`, which I think is intuitive, but could lead to situation where the pointer is cloned before calling `From`, and its second instance is used somewhere else. Unless we will make instances created by `From` always check the position from godot, and the one that never gave its inner pointer use the internal position... unless there are some additional caveats in pointer movements that I'm not aware of, which is likely. Thats why after considering it I deem the pointer-tracking in `GFile` mid-risk low-reward, so better to drop it completely

**Comment by Bromeon** [comment] 2023-11-10 11:25
> Renaming the functions to `read_*` and `write_*` could actually make a clash with some FileAccess methods. Eg. `Read` provides `read_line()` method, which returns `String`, but there is `get_line()` method on FileAccess that returns `GodotString` - unless we want to ditch the `GodotString` returning method for `String` returning one.

Good point, maybe `get_line` could then be renamed to `get_line_gstring` or so.



> I think we also should mark the _reexports_ through the `GFile` (like these `get_` methods somehow, to make it obvious that they are just thin wrapper.

Why? From the user perspective, it doesn't matter. They just want to read/write files.
Where distinction matters is if the involved types are `String` or `GodotString`, and I agree this could be named accordingly.



> So I guess I should make the `get_*` methods intake `&mut self`?

Yes, would be nice! 🙂 
Also added a lot of comments in the PR itself. Let's maybe continue there to avoid parallel discussion.

**Closed** 2023-11-19 12:02 UTC
Labels: feature, c: engine
